name = "p2pos"
compatibility_date = "2026-02-21"

workers_dev = false

[[routes]]
pattern = "p2pos.zhongwwwhhh.cc"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
